Untitled2/Untitled2/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Untitled2.Models;
using System.Security.Claims;
using Untitled2.Repository;

namespace Untitled2.Controllers
{
    public class CartController : Controller
    {
        private readonly StoreRepository rep = new StoreRepository();

        // GET: Cart
        [Route("cart")]
        public ActionResult Index()
        {
            int id = 0;
            StoreItem status = new StoreItem();
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                // the principal identity is a claims identity.
                // now we need to find the NameIdentifier claim
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    id = Convert.ToInt32(userIdClaim.Value);
                }
            }

            if (id == 0)
            {
                var anonCart = new Cart();

                if (Session["__MySessionCart"] == null)
                {
                    anonCart = new Cart() { };
                    anonCart.Id = -1;
                    anonCart.Uid = new Guid();
                    anonCart.CartItems = new List<StoreItem>();

                    Session["__MySessionCart"] = anonCart;
                }

                return View(Session["__MySessionCart"]);
            }
            else
            {
                var cart = rep.GetCartAndItems(id);

                return View(cart);
            }
        }

        [Route("cart/summary")]
        public PartialViewResult Summary(Cart cart)
        {
            int id = 0;
            StoreItem status = new StoreItem();
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                // the principal identity is a claims identity.
                // now we need to find the NameIdentifier claim
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    id = Convert.ToInt32(userIdClaim.Value);
                }
            }

            if (id == 0)
            {
                var anonCart = new Cart();

                if (Session["__MySessionCart"] == null)
                {
                    anonCart = new Cart() { };
                    anonCart.Id = 0;
                    anonCart.Uid = Guid.NewGuid();
                    anonCart.CartItems = new List<StoreItem>();

                    Session["__MySessionCart"] = anonCart;
                }
                var cart1 = new Cart();
                var sCart = (Cart)Session["__MySessionCart"];

                cart1.Quantity = sCart.Quantity;
                cart1.TotalPrice = sCart.TotalPrice;

                return PartialView(cart1);
            }
            else
            {
                ViewData["myCart"] = rep.GetCart(id);
                return PartialView(ViewData["myCart"]);
            }
        }

        [Route("cart/cartdetails")]
        public JsonResult CartDetails()
        {
            int id = 0;
            StoreItem status = new StoreItem();
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                // the principal identity is a claims identity.
                // now we need to find the NameIdentifier claim
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    id = Convert.ToInt32(userIdClaim.Value);
                }
            }
            var cart = rep.GetCart(id);

            if (id == 0)
            {
                if (cart == null)
                {
                    cart = (Cart)Session["__MySessionCart"];

                    if (cart != null)
                    {
                        return Json(cart, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(null, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            else
            {
                return Json(cart, JsonRequestBehavior.AllowGet);
            }

            return Json(null, JsonRequestBehavior.AllowGet);
        }

        [Route("cart/checkout")]
        public ActionResult Checkout()
        {
            return View();
        }
    }
}

Untitled2/Untitled2/Views/Shared/Blank.cshtml
<!DOCTYPE html>
<html class="@RenderSection("htmlClass", false)">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Untitled Webpages</title>
        @Scripts.Render("~/Scripts/third-party/bundle")
        @Scripts.Render("~/Scripts/AppScripts")
            @Styles.Render("~/Content/site")
                @Styles.Render("~/bundles/bootstrapcss")
                @Styles.Render("~/Content/jQueryUi")
    
    <style>
        html {
            min-height: 100%; /* make sure it is at least as tall as the viewport */
            position: relative;
        }

        body {
            height: 100%; /* force the BODY element to match the height of the HTML element */
        }
    </style>
</head>

<body>
    @RenderBody()

    <script type="text/javascript">
        App.configure({
            appBase: '@Url.Content("~")',
            secureAppBase: '@Url.Content("~")',
            passwordComplexity: {
                minLength: 8,
                uppercaseCharacters: 1,
                lowercaseCharacters: 1,
                numberCharacters: 1,
                specialCharacters: 1,
                message: "This field must be at least 8 characters, and contain at least 1 uppercase, lowercase, number, and special character."
            }
        });
    </script>

    @RenderSection("scripts", required: false)
</body>

</html>

Untitled2/Untitled2/Views/Shared/BlankCalendar.cshtml
<!DOCTYPE html>
<html class="@RenderSection("htmlClass", false)">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.GetPageTitle()</title>
    @Scripts.Render("~/Scripts/jquery-2.2.3/bundle")
    @Scripts.Render("~/Scripts/bootstrap/bundle")
    @Scripts.Render("~/Scripts/moment/bundle")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker/bundle")

    @Scripts.Render("~/Scripts/third-party/bundle")
        @Scripts.Render("~/Scripts/AppScripts")

        @Styles.Render("~/Content/site")
        @Styles.Render("~/bundles/bootstrap-datetimepicker")
        @Styles.Render("~/bundles/bootstrapcss")
        @Styles.Render("~/Content/jQueryUi")
    <style>
        html {
            min-height: 100%; /* make sure it is at least as tall as the viewport */
            position: relative;
        }

        body {
            height: 100%; /* force the BODY element to match the height of the HTML element */
        }
    </style>
</head>

<body>
    @RenderBody()
    <script type="text/javascript">
        console.log('@Url.Content("~")');
        console.log(window.location.protocol + '//' + window.location.host);
        App.configure({
            appBase: '@Url.Content("~")',
            secureAppBase: '@Url.Content("~")',
            passwordComplexity: {
                minLength: 8,
                uppercaseCharacters: 1,
                lowercaseCharacters: 1,
                numberCharacters: 1,
                specialCharacters: 1,
                message: "This field must be at least 8 characters, and contain at least 1 uppercase, lowercase, number, and special character."
            }
        });
    </script>

    @RenderSection("scripts", required: false)
</body>

</html>

Untitled2/Untitled2/Views/Shared/BlankSearch.cshtml
<!DOCTYPE html>
<html class="@RenderSection("htmlClass", false)">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Untitled Webpages</title>    
    
    @Scripts.Render("~/Scripts/LuceneSearch")
    @Styles.Render("~/Content/LuceneSearch")
    <style>
        html {
            min-height: 100%; /* make sure it is at least as tall as the viewport */
            position: relative;
        }

        body {
            height: 100%; /* force the BODY element to match the height of the HTML element */
        }
    </style>    

</head>

<body>
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>

</html>

Untitled2/Untitled2/Views/Shared/FullScreenCalendar.cshtml
@{
    Layout = "~/Views/Shared/BlankCalendar.cshtml";

}


<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="~/">Untitled Webpages</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="~/">Home</a></li>
            <li><a href="~/Stores">Store</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Live Game<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="~/Game">Live Game</a></li>
                </ul>
            </li>
            <li><a href="~/Games/Asteroid">Asteroid Game</a></li>
            <li><a href="~/Calendar">Event Calendar</a></li>
            <li><a href="~/Home/Map">Google Maps Tool</a></li>
            <li><a href="~/ToDoList">To Do List</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="padding-right:20px;">
            @using (Html.BeginForm("LocalizationAction", "LocalizationController", new { returnUrl = Request.Url.AbsoluteUri }))
            {

                if (Request.IsAuthenticated)
                {

                    <li>
                        @Html.ActionLink(HttpContext.Current.User.Identity.Name, "Profile", "Home", new { id = HttpContext.Current.User.Identity.Name })
                    </li>
                    <li>
                        <a href="~/account/logoff">SignOut</a>
                    </li>
                    <li>
                    </li>
                }
                else
                {
                    <li> @Html.ActionLink("Sign in", "Login", "Account", new { r = Request.Url.AbsolutePath.ToString() }, new { @class = "hoverbutton" }) @Html.ActionLink("Register", "Register", "Account", null, new { @class = "hoverbutton" }) </li>
                }
            }
        </ul>
    </div>
</nav>
<div id="main-wrapper" class="col-md-11 pull-right">
    <div class="container-fluid body-content" style="padding-bottom: 80px;">
        @RenderBody()
    </div>
</div>
<div class="navbar-fixed-bottom">
    <div style="padding:10px; background-color:#E7E7E7 ">
        &copy; Untitled Webpages
    </div>
</div>

@section scripts
{
    @RenderSection("scripts", false)
}
<script type="text/javascript">
    $(".nav li").on("click", function () {
        $(".nav li").removeClass("active");
    });

    var url = window.location;
    // Will only work if string in href matches with location
    $('ul.nav a[href="' + url + '"]').parent().addClass('active');

    // Will also work for relative and absolute hrefs
    $('ul.nav a').filter(function () {
        return this.href == url;
    }).parent().addClass('active');

    //var viewModel = new App.Layout({});
    //App.bindViewModel({ viewModel: viewModel, elementId: "wrapper" });
</script>

Untitled2/Untitled2/Views/Shared/Fullscreen.cshtml
@{
    Layout = "~/Views/Shared/Blank.cshtml";

}


@*@helper UserItemTemplate(string id, string title)
{
    <div id="@id" class="option" data-bind="click: @(id)Click">
        <div class="iconWrapper">
            <div class="image"></div>
        </div>
        <div class="label">
            <div class="title">@title</div>
        </div>
    </div>
}*@

@*<div id="header1">
        <div style="max-width:1500px; margin:auto;">
            @*<a href="~/Stores" style="text-decoration:none;">
                <div style="display:inline-block; border-right: 2px solid #333333; padding:20px; margin-top:4px; margin-left: -4px;">
                    Store
                </div>
            </a>
            <a href="~/Games" style="text-decoration:none;">
                <div style="display:inline-block; border-right: 2px solid #333333; padding:20px; margin-top:4px; margin-left: -4px;">
                    Live Game
                </div>
            </a>
            <a href="~/Games/Asteroid" style="text-decoration:none;">
                <div style="display:inline-block; border-right: 2px solid #333333; padding:20px; margin-top:4px; margin-left: -4px;">
                    Asteroid Game
                </div>
            </a>
            <a href="~/ToDoList" style="text-decoration:none;">
                <div style="display:inline-block; padding:20px; margin-top:4px; margin-left: -4px;">
                    To Do List
                </div>
            </a>
            <div id="userMenuOptions" style="z-index:100;float:right;">
                @Html.AntiForgeryToken()
                @UserItemTemplate("logout", "LOG OUT")
                @Html.Partial("~/views/shared/SignIn.cshtml")
            </div>
        </div>
    </div>*@
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="~/">Untitled Webpages</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="~/">Home</a></li>
            <li><a href="~/Stores">Store</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Live Game<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="~/Game">Live Game</a></li>
                </ul>
            </li>
            <li><a href="~/Games/Asteroid">Asteroid Game</a></li>
            <li><a href="~/Calendar">Event Calendar</a></li>
            <li><a href="~/Home/Map">Google Maps Tool</a></li>
            <li><a href="~/ToDoList">To Do List</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="padding-right:20px;">
            @using (Html.BeginForm("LocalizationAction", "LocalizationController", new { returnUrl = Request.Url.AbsoluteUri }))
            {

                if (Request.IsAuthenticated)
                {

                    <li>
                        @Html.ActionLink(HttpContext.Current.User.Identity.Name, "Profile", "Home", new { id = HttpContext.Current.User.Identity.Name })
                    </li>
                    <li>
                        <a href="~/account/logoff">SignOut</a>
                    </li>
                    <li>
                    </li>
                }
                else
                {
                    <li> @Html.ActionLink("Sign in", "Login", "Account", new { r = Request.Url.AbsolutePath.ToString() }, new { @class = "hoverbutton" }) @Html.ActionLink("Register", "Register", "Account", null, new { @class = "hoverbutton" }) </li>
                }
            }
        </ul>
    </div>
</nav>
<div id="main-wrapper" class="col-md-11 pull-right">
    <div class="container-fluid body-content" style="padding-bottom: 80px;">
        @RenderBody()
    </div>
</div>
<div class="navbar-fixed-bottom">
    <div style="padding:10px; background-color:#E7E7E7 ">
        &copy; Untitled Webpages
    </div>
</div>

@section scripts
{
    @RenderSection("scripts", false)
}
<script type="text/javascript">
    $(".nav li").on("click", function () {
        $(".nav li").removeClass("active");
    });

    var url = window.location;
    // Will only work if string in href matches with location
    $('ul.nav a[href="' + url + '"]').parent().addClass('active');

    // Will also work for relative and absolute hrefs
    $('ul.nav a').filter(function () {
        return this.href == url;
    }).parent().addClass('active');

    //var viewModel = new App.Layout({});
    //App.bindViewModel({ viewModel: viewModel, elementId: "wrapper" });
</script>

Untitled2/Untitled2/Views/Shared/HomepageLayout.cshtml
@{
    Layout = "~/Views/Shared/Blank.cshtml";

}

@helper UserItemTemplate(string id, string title)
{
    <div id="@id" class="option" data-bind="click: @(id)Click">
        <div class="iconWrapper">
            <div class="image"></div>
        </div>
        <div class="label">
            <div class="title">@title</div>
        </div>
    </div>
}

@*<div id="header1">
        <div style="max-width:1500px; margin:auto;">
            @*<a href="~/Stores" style="text-decoration:none;">
                <div style="display:inline-block; border-right: 2px solid #333333; padding:20px; margin-top:4px; margin-left: -4px;">
                    Store
                </div>
            </a>
            <a href="~/Games" style="text-decoration:none;">
                <div style="display:inline-block; border-right: 2px solid #333333; padding:20px; margin-top:4px; margin-left: -4px;">
                    Live Game
                </div>
            </a>
            <a href="~/Games/Asteroid" style="text-decoration:none;">
                <div style="display:inline-block; border-right: 2px solid #333333; padding:20px; margin-top:4px; margin-left: -4px;">
                    Asteroid Game
                </div>
            </a>
            <a href="~/ToDoList" style="text-decoration:none;">
                <div style="display:inline-block; padding:20px; margin-top:4px; margin-left: -4px;">
                    To Do List
                </div>
            </a>
            <div id="userMenuOptions" style="z-index:100;float:right;">
                @Html.AntiForgeryToken()
                @UserItemTemplate("logout", "LOG OUT")
                @Html.Partial("~/views/shared/SignIn.cshtml")
            </div>
        </div>
    </div>*@
<nav class="navbar navbar-default" style="margin-bottom:0">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="~/">Untitled Webpages</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="~/">Home</a></li>
            <li><a href="~/Stores">Store</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Live Game
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="~/Game">Live Game</a></li>
                </ul>
            </li>
            <li><a href="~/Games/Asteroid">Asteroid Game</a></li>
            <li><a href="~/Calendar">Event Calendar</a></li>
            <li><a href="~/Home/Map">Google Maps Tool</a></li>
            <li><a href="~/ToDoList">To Do List</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="padding-right:20px;">
            @using (Html.BeginForm("LocalizationAction", "LocalizationController", new { returnUrl = Request.Url.AbsoluteUri }))
            {

                if (Request.IsAuthenticated)
                {

                    <li>
                        @Html.ActionLink(HttpContext.Current.User.Identity.Name, "Profile", "Home", new { id = HttpContext.Current.User.Identity.Name })
                    </li>
                    <li>
                        <a href="~/account/logoff">SignOut</a>
                    </li>
                    <li>
                    </li>
                }
                else
                {
                    <li> @Html.ActionLink("Sign in", "Login", "Account", new { r = Request.Url.AbsolutePath.ToString() }, new { @class = "hoverbutton" }) @Html.ActionLink("Register", "Register", "Account", null, new { @class = "hoverbutton" }) </li>
                }
            }
        </ul>
    </div>
</nav>
<div>
    <div class="container-full" style="padding-bottom: 80px;
  margin: 0 auto;
  width: 100%;">
        @RenderBody()
    </div>
</div>
<div class="navbar-fixed-bottom">
    <div style="padding:10px; background-color:#E7E7E7 ">
        &copy; 2016 Untitled Webpages
    </div>
</div>
@section scripts
{
    @RenderSection("scripts", false)
}
<script type="text/javascript">
    $(".nav li").on("click", function () {
        $(".nav li").removeClass("active");
    });

    var url = window.location;
    // Will only work if string in href matches with location
    $('ul.nav a[href="' + url + '"]').parent().addClass('active');

    // Will also work for relative and absolute hrefs
    $('ul.nav a').filter(function () {
        return this.href == url;
    }).parent().addClass('active');

    var viewModel = new App.Layout({});
    App.bindViewModel({ viewModel: viewModel, elementId: "wrapper" });
</script>
<style>
</style>

Untitled2/Untitled2/Views/Shared/Login.cshtml
@model Untitled2.Views.Account.LoginViewModel

@{
    Layout = "~/Views/Shared/Blank.cshtml";
}


<style>
    .labelWrapper {
        width: 160px;
    }

    .field {
        clear: both;
        width: 100%;
    }

    .inputWrapper {
        float: left;
        width: 280px;
    }

    input {
        width: 400px;
        height: 30px;
        font-size: 18px;
    }
</style>



<div id="loginContainer" style="height: 100%;">
    <div style="position:relative;height: 100%;margin-right:40px;">
        <div style="position: absolute; top: 20%; left:10%; background-color: whitesmoke; width: 700px; height: 450px; opacity: .7; padding:40px 20px 20px 60px;">
            <div id="titleWrapper">
                <div id="logo">
                    <div class="image"></div>
                </div>
                <div id="title">
                    <div style="font-size:48px;">
                        Login
                    </div>
                </div>
            </div>
            <div id="description">
                <p>
                    <b>Welcome!</b> Please Login below.
                </p>
                <p>
                    If this is your first visit to our site, select <b>Register</b> and create your account today!!!
                </p>
            </div>
            <form id="loginpage" method="POST" action="login">
                <div id="loginStatus">
                    @if (!Model.ErrorMessage.IsNullOrEmpty())
                    {
                        @Model.ErrorMessage
                    }
                </div>
                <div style="margin-top:40px;">
                    @Html.AntiForgeryToken()
                    <div id="input">
                        <div style="margin:10px 0;">@Html.TextField("username", "username", "USERNAME")</div>
                        <div style="">@Html.PasswordField("password", "password", "PASSWORD")</div>
                    </div>
                    <div id="actions">
                        <div>
                            <div id="login" class="actionButton">
                                <input type="submit" data-bind="click: login" style="width:100px;" value="LOG IN" />
                            </div>
                        </div>
                        <div>
                            <div id="register" class="actionButton">
                                <a href="@Url.Action("Register", "Account")">
                                    <div>REGISTER</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript">
    App.configure({
        appBase: '@Url.Content("~")',
        secureAppBase: '@Url.Content("~")',
            passwordComplexity: {
                minLength: 8,
                uppercaseCharacters: 1,
                lowercaseCharacters: 1,
                numberCharacters: 1,
                specialCharacters: 1,
                message: "This field must be at least 8 characters, and contain at least 1 uppercase, lowercase, number, and special character."
            }
    });
        var viewModel = new App.Login(@Model.ToJson());
    ko.applyBindings(viewModel, document.getElementById('loginpage'));
    </script>
}

Untitled2/Untitled2/Views/Shared/SignIn.cshtml
@using Untitled2
@*@{
    AppUserState appUserState = (AppUserState)this.ViewData["UserState"];
}*@
@using (Html.BeginForm("LocalizationAction", "LocalizationController", new { returnUrl = Request.Url.AbsoluteUri }))
{

    if (Request.IsAuthenticated)
    {

        <li>
            @Html.ActionLink(HttpContext.Current.User.Identity.Name, "Profile", "Home", new { id = HttpContext.Current.User.Identity.Name }) |
        </li><li>
            @Html.ActionLink("Sign out", "LogOff", "Account", null)
        </li>
    }
    else
    {
        <li> @Html.ActionLink("Sign in", "Login", "Account", new { r = Request.Url.AbsolutePath.ToString() }, new { @class = "hoverbutton" }) @Html.ActionLink("Register", "Register", "Account", null, new { @class = "hoverbutton" }) </li>
    }
}
<style>
    .hoverbutton {
        cursor: pointer;
    }
</style>

Untitled2/Untitled2/Views/Shared/StoreLayout.cshtml
@{
    Layout = "~/Views/Shared/Blank.cshtml";
}

@helper UserItemTemplate(string id, string title)
{
    <div id="@id" class="option" data-bind="click: @(id)Click">
        <div class="iconWrapper">
            <div class="image"></div>
        </div>
        <div class="label">
            <div class="title">@title</div>
        </div>
    </div>
}


<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="~/">Untitled Webpages</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="~/">Home</a></li>
            <li><a href="~/Stores">Store</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Live Game<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="~/Game">Live Game</a></li>
                </ul>
            </li>
            <li><a href="~/Games/Asteroid">Asteroid Game</a></li>
            <li><a href="~/Calendar">Event Calendar</a></li>
            <li><a href="~/Home/Map">Google Maps Tool</a></li>
            <li><a href="~/ToDoList">To Do List</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="padding-right:20px;">
            @using (Html.BeginForm("LocalizationAction", "LocalizationController", new { returnUrl = Request.Url.AbsoluteUri }))
            {

                if (Request.IsAuthenticated)
                {

                    <li>
                        @Html.ActionLink(HttpContext.Current.User.Identity.Name, "Profile", "Home", new { id = HttpContext.Current.User.Identity.Name })
                    </li>
                    <li>
                        <a href="~/account/logoff">SignOut</a>
                    </li>
                    <li>
                    </li>
                }
                else
                {
                    <li> @Html.ActionLink("Sign in", "Login", "Account", new { r = Request.Url.AbsolutePath.ToString() }, new { @class = "hoverbutton" }) @Html.ActionLink("Register", "Register", "Account", null, new { @class = "hoverbutton" }) </li>
                }
            }
        </ul>
    </div>
</nav>
<div id="main-wrapper" class="col-md-11">
    <div class="container-fluid body-content" style="padding-bottom: 60px;">
        <div style="position:relative;">
            <div style="position:absolute; right:0; top:0;">
                @Html.Action("Summary", "Cart", ViewData["myCart"])
            </div>
        </div>
        <div>
            @RenderBody()
        </div>
        <div style="clear:both;">
        </div>
    </div>
</div>
<div class="navbar-fixed-bottom">
    <div style="padding:10px; background-color:#E7E7E7;">
        &copy; Untitled Webpages
    </div>
</div>

@section scripts
{
    @RenderSection("scripts", false)
}
<script type="text/javascript">
    var viewModel = new App.Layout({});
    App.bindViewModel({ viewModel: viewModel, elementId: "wrapper" });

    $(".nav li").on("click", function () {
        $(".nav li").removeClass("active");
    });
    $('ul.nav a[href="' + url + '"]').parent().addClass('active');

    // Will also work for relative and absolute hrefs
    $('ul.nav a').filter(function () {
        return this.href == url;
    }).parent().addClass('active');
</script>

Untitled2/Untitled2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>